// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Account stores non-secret account metadata.
 * Secrets (api key, cf_clearance, user-agent) are stored in OS keychain.
 */
export class Account {
    "id": string;
    "label": string;
    "mirror": string;
    "currency": string;
    "profileId": string;
    "connectionState": string;
    "lastCheckAt"?: string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Account instance. */
    constructor($$source: Partial<Account> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("mirror" in $$source)) {
            this["mirror"] = "";
        }
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("connectionState" in $$source)) {
            this["connectionState"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     */
    static createFrom($$source: any = {}): Account {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account($$parsedSource as Partial<Account>);
    }
}

/**
 * ActiveStatus is the frontend-facing connected session state.
 */
export class ActiveStatus {
    "connected": boolean;
    "state": string;
    "reason"?: StateReason;
    "lastCheckAt"?: string;
    "accountId"?: string;
    "account"?: Account | null;
    "error"?: string;
    "balances"?: SessionBalance[];

    /** Creates a new ActiveStatus instance. */
    constructor($$source: Partial<ActiveStatus> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveStatus {
        const $$createField2_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reason" in $$parsedSource) {
            $$parsedSource["reason"] = $$createField2_0($$parsedSource["reason"]);
        }
        if ("account" in $$parsedSource) {
            $$parsedSource["account"] = $$createField5_0($$parsedSource["account"]);
        }
        if ("balances" in $$parsedSource) {
            $$parsedSource["balances"] = $$createField7_0($$parsedSource["balances"]);
        }
        return new ActiveStatus($$parsedSource as Partial<ActiveStatus>);
    }
}

/**
 * ConnectionCheckResult contains outcomes for all connection check steps.
 */
export class ConnectionCheckResult {
    "ok": boolean;
    "state": string;
    "reason"?: StateReason;
    "lastCheckAt"?: string;
    "steps": ConnectionStep[];

    /** Creates a new ConnectionCheckResult instance. */
    constructor($$source: Partial<ConnectionCheckResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("steps" in $$source)) {
            this["steps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionCheckResult {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reason" in $$parsedSource) {
            $$parsedSource["reason"] = $$createField2_0($$parsedSource["reason"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField4_0($$parsedSource["steps"]);
        }
        return new ConnectionCheckResult($$parsedSource as Partial<ConnectionCheckResult>);
    }
}

/**
 * ConnectionStep reports a single step in connection checks.
 */
export class ConnectionStep {
    "name": string;
    "success": boolean;
    "message"?: string;

    /** Creates a new ConnectionStep instance. */
    constructor($$source: Partial<ConnectionStep> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStep instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionStep {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStep($$parsedSource as Partial<ConnectionStep>);
    }
}

/**
 * SecretsMasked returns only availability flags to avoid exposing secrets in UI/API.
 */
export class SecretsMasked {
    "hasApiKey": boolean;
    "hasClearance": boolean;
    "hasUserAgent": boolean;

    /** Creates a new SecretsMasked instance. */
    constructor($$source: Partial<SecretsMasked> = {}) {
        if (!("hasApiKey" in $$source)) {
            this["hasApiKey"] = false;
        }
        if (!("hasClearance" in $$source)) {
            this["hasClearance"] = false;
        }
        if (!("hasUserAgent" in $$source)) {
            this["hasUserAgent"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecretsMasked instance from a string or object.
     */
    static createFrom($$source: any = {}): SecretsMasked {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecretsMasked($$parsedSource as Partial<SecretsMasked>);
    }
}

/**
 * SessionBalance is a simplified balance entry for frontend rendering.
 */
export class SessionBalance {
    "currency": string;
    "available": number;
    "vault": number;

    /** Creates a new SessionBalance instance. */
    constructor($$source: Partial<SessionBalance> = {}) {
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = 0;
        }
        if (!("vault" in $$source)) {
            this["vault"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionBalance instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionBalance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionBalance($$parsedSource as Partial<SessionBalance>);
    }
}

/**
 * StateReason gives the frontend a stable machine-readable reason plus a
 * user-facing message for the current account/session state.
 */
export class StateReason {
    "code"?: string;
    "message"?: string;

    /** Creates a new StateReason instance. */
    constructor($$source: Partial<StateReason> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StateReason instance from a string or object.
     */
    static createFrom($$source: any = {}): StateReason {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StateReason($$parsedSource as Partial<StateReason>);
    }
}

// Private type creation functions
const $$createType0 = StateReason.createFrom;
const $$createType1 = Account.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = SessionBalance.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ConnectionStep.createFrom;
const $$createType6 = $Create.Array($$createType5);
