// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ChartPoint is a single data point for the profit chart.
 */
export class ChartPoint {
    "x": number;
    "y": number;
    "win": boolean;

    /** Creates a new ChartPoint instance. */
    constructor($$source: Partial<ChartPoint> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("win" in $$source)) {
            this["win"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): ChartPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChartPoint($$parsedSource as Partial<ChartPoint>);
    }
}

/**
 * LogEntry represents a single log message from the script.
 */
export class LogEntry {
    "time": time$0.Time;
    "message": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("time" in $$source)) {
            this["time"] = null;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

/**
 * SafetyLimits are hard backend rails for automated sessions. They apply to
 * both simulated and live modes, but live sessions should always provide
 * non-zero limits.
 */
export class SafetyLimits {
    "maxBets": number;
    "maxBetAmount": number;
    "stopLoss": number;
    "takeProfit": number;

    /** Creates a new SafetyLimits instance. */
    constructor($$source: Partial<SafetyLimits> = {}) {
        if (!("maxBets" in $$source)) {
            this["maxBets"] = 0;
        }
        if (!("maxBetAmount" in $$source)) {
            this["maxBetAmount"] = 0;
        }
        if (!("stopLoss" in $$source)) {
            this["stopLoss"] = 0;
        }
        if (!("takeProfit" in $$source)) {
            this["takeProfit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SafetyLimits instance from a string or object.
     */
    static createFrom($$source: any = {}): SafetyLimits {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SafetyLimits($$parsedSource as Partial<SafetyLimits>);
    }
}
