// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GameSpec provides metadata about a game
 */
export class GameSpec {
    "id": string;
    "name": string;
    "metric_label": string;

    /** Creates a new GameSpec instance. */
    constructor($$source: Partial<GameSpec> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("metric_label" in $$source)) {
            this["metric_label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): GameSpec {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameSpec($$parsedSource as Partial<GameSpec>);
    }
}
