// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as games$0 from "../internal/games/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelRun stops an in-progress scan
 */
export function CancelRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3520137843, runID);
}

/**
 * ExportRunCSV exports all hits for a run as a CSV string.
 * Returns the CSV content as a string that the frontend can download.
 */
export function ExportRunCSV(runID: string): $CancellablePromise<string> {
    return $Call.ByID(3093482705, runID);
}

export function GetGames(): $CancellablePromise<games$0.GameSpec[]> {
    return $Call.ByID(2287680007).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetKenoRisks returns the available risk levels for Keno
 */
export function GetKenoRisks(): $CancellablePromise<string[]> {
    return $Call.ByID(2439414625).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRun retrieves individual run metadata and summary
 */
export function GetRun(runID: string): $CancellablePromise<store$0.Run | null> {
    return $Call.ByID(2920806369, runID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetRunHits retrieves hits for a run with server-side pagination and delta nonce calculation
 */
export function GetRunHits(runID: string, page: number, perPage: number): $CancellablePromise<$models.HitsPage | null> {
    return $Call.ByID(1305181983, runID, page, perPage).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetSeedRuns returns every run that shares the server/client seed combo of the provided run ID
 */
export function GetSeedRuns(runID: string): $CancellablePromise<$models.SeedRunGroup | null> {
    return $Call.ByID(1674687991, runID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function HashServerSeed(server: string): $CancellablePromise<string> {
    return $Call.ByID(2101313278, server);
}

/**
 * ListRuns retrieves runs with pagination and game-based filtering
 */
export function ListRuns(query: $models.RunsQuery): $CancellablePromise<$models.RunsList | null> {
    return $Call.ByID(612452562, query).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * StartKenoB2BScan starts a Keno B2B scan
 */
export function StartKenoB2BScan(req: $models.KenoB2BRequest): $CancellablePromise<$models.KenoB2BResult> {
    return $Call.ByID(1558459286, req).then(($result: any) => {
        return $$createType11($result);
    });
}

export function StartScan(req: $models.ScanRequest): $CancellablePromise<$models.ScanResult> {
    return $Call.ByID(1705255349, req).then(($result: any) => {
        return $$createType12($result);
    });
}

export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(2757383401);
}

// Private type creation functions
const $$createType0 = games$0.GameSpec.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = store$0.Run.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.HitsPage.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.SeedRunGroup.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.RunsList.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.KenoB2BResult.createFrom;
const $$createType12 = $models.ScanResult.createFrom;
