// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthModule exposes stakeauth.Module through the bindings package.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stake$0 from "../internal/stake/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stakeauth$0 from "../internal/stakeauth/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

export function ActiveConnectionState(): $CancellablePromise<string> {
    return $Call.ByID(3875644724);
}

/**
 * SessionProvider methods used by ScriptModule.
 */
export function Client(): $CancellablePromise<stake$0.Client | null> {
    return $Call.ByID(353257418).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(851067221, id);
}

export function ConnectionCheck(id: string): $CancellablePromise<stakeauth$0.ConnectionCheckResult> {
    return $Call.ByID(1849275919, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(3298351529, id);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(293343927);
}

export function GetActiveStatus(): $CancellablePromise<stakeauth$0.ActiveStatus> {
    return $Call.ByID(1333025959).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetSecretsMasked(id: string): $CancellablePromise<stakeauth$0.SecretsMasked> {
    return $Call.ByID(553554681, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function IsConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(3621455820);
}

export function ListAccounts(): $CancellablePromise<stakeauth$0.Account[]> {
    return $Call.ByID(512896965).then(($result: any) => {
        return $$createType6($result);
    });
}

export function OpenCasinoInBrowser(id: string): $CancellablePromise<void> {
    return $Call.ByID(1308490247, id);
}

export function RepairSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(794317780, id);
}

export function SaveAccount(acct: stakeauth$0.Account): $CancellablePromise<stakeauth$0.Account> {
    return $Call.ByID(2965893371, acct).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2555826015, app);
}

export function SetSecrets(id: string, apiKey: string, clearance: string, userAgent: string): $CancellablePromise<void> {
    return $Call.ByID(1791447588, id, apiKey, clearance, userAgent);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(2613479367);
}

export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(770055622);
}

// Private type creation functions
const $$createType0 = stake$0.Client.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = stakeauth$0.ConnectionCheckResult.createFrom;
const $$createType3 = stakeauth$0.ActiveStatus.createFrom;
const $$createType4 = stakeauth$0.SecretsMasked.createFrom;
const $$createType5 = stakeauth$0.Account.createFrom;
const $$createType6 = $Create.Array($$createType5);
