// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scripting$0 from "../internal/scripting/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

/**
 * B2BSequence represents a streak of consecutive wins
 */
export class B2BSequence {
    "startNonce": number;
    "endNonce": number;
    "cumulativeMultiplier": number;
    "streakLength": number;
    "bets": KenoBet[];

    /** Creates a new B2BSequence instance. */
    constructor($$source: Partial<B2BSequence> = {}) {
        if (!("startNonce" in $$source)) {
            this["startNonce"] = 0;
        }
        if (!("endNonce" in $$source)) {
            this["endNonce"] = 0;
        }
        if (!("cumulativeMultiplier" in $$source)) {
            this["cumulativeMultiplier"] = 0;
        }
        if (!("streakLength" in $$source)) {
            this["streakLength"] = 0;
        }
        if (!("bets" in $$source)) {
            this["bets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new B2BSequence instance from a string or object.
     */
    static createFrom($$source: any = {}): B2BSequence {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bets" in $$parsedSource) {
            $$parsedSource["bets"] = $$createField4_0($$parsedSource["bets"]);
        }
        return new B2BSequence($$parsedSource as Partial<B2BSequence>);
    }
}

export class Hit {
    "Nonce": number;
    "Metric": number;

    /** Creates a new Hit instance. */
    constructor($$source: Partial<Hit> = {}) {
        if (!("Nonce" in $$source)) {
            this["Nonce"] = 0;
        }
        if (!("Metric" in $$source)) {
            this["Metric"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hit instance from a string or object.
     */
    static createFrom($$source: any = {}): Hit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hit($$parsedSource as Partial<Hit>);
    }
}

/**
 * HitsPage represents paginated hits response with delta nonce calculation
 */
export class HitsPage {
    "hits": store$0.HitWithDelta[];
    "totalCount": number;
    "page": number;
    "perPage": number;
    "totalPages": number;

    /** Creates a new HitsPage instance. */
    constructor($$source: Partial<HitsPage> = {}) {
        if (!("hits" in $$source)) {
            this["hits"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("perPage" in $$source)) {
            this["perPage"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HitsPage instance from a string or object.
     */
    static createFrom($$source: any = {}): HitsPage {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField0_0($$parsedSource["hits"]);
        }
        return new HitsPage($$parsedSource as Partial<HitsPage>);
    }
}

/**
 * KenoB2BRequest represents a Keno B2B scan request from the frontend
 */
export class KenoB2BRequest {
    "seeds": Seeds;

    /**
     * Accept both string and uint64
     */
    "nonceStart": any;

    /**
     * Accept both string and uint64
     */
    "nonceEnd": any;

    /**
     * "classic", "low", "medium", "high"
     */
    "risk": string;

    /**
     * 1-10
     */
    "pickCount": number;

    /**
     * "reproducible" or "entropy"
     */
    "pickerMode": string;

    /**
     * Minimum cumulative multiplier
     */
    "b2bThreshold": number;

    /**
     * 0 = find all, >0 = limit
     */
    "topN": number;

    /** Creates a new KenoB2BRequest instance. */
    constructor($$source: Partial<KenoB2BRequest> = {}) {
        if (!("seeds" in $$source)) {
            this["seeds"] = (new Seeds());
        }
        if (!("nonceStart" in $$source)) {
            this["nonceStart"] = null;
        }
        if (!("nonceEnd" in $$source)) {
            this["nonceEnd"] = null;
        }
        if (!("risk" in $$source)) {
            this["risk"] = "";
        }
        if (!("pickCount" in $$source)) {
            this["pickCount"] = 0;
        }
        if (!("pickerMode" in $$source)) {
            this["pickerMode"] = "";
        }
        if (!("b2bThreshold" in $$source)) {
            this["b2bThreshold"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KenoB2BRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): KenoB2BRequest {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("seeds" in $$parsedSource) {
            $$parsedSource["seeds"] = $$createField0_0($$parsedSource["seeds"]);
        }
        return new KenoB2BRequest($$parsedSource as Partial<KenoB2BRequest>);
    }
}

/**
 * KenoB2BResult contains the results of a Keno B2B scan
 */
export class KenoB2BResult {
    "sequences": B2BSequence[];
    "totalFound": number;
    "highestMulti": number;
    "totalEvaluated": number;
    "antebotScript"?: string;

    /** Creates a new KenoB2BResult instance. */
    constructor($$source: Partial<KenoB2BResult> = {}) {
        if (!("sequences" in $$source)) {
            this["sequences"] = [];
        }
        if (!("totalFound" in $$source)) {
            this["totalFound"] = 0;
        }
        if (!("highestMulti" in $$source)) {
            this["highestMulti"] = 0;
        }
        if (!("totalEvaluated" in $$source)) {
            this["totalEvaluated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KenoB2BResult instance from a string or object.
     */
    static createFrom($$source: any = {}): KenoB2BResult {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sequences" in $$parsedSource) {
            $$parsedSource["sequences"] = $$createField0_0($$parsedSource["sequences"]);
        }
        return new KenoB2BResult($$parsedSource as Partial<KenoB2BResult>);
    }
}

/**
 * KenoBet represents a single Keno bet in a B2B sequence
 */
export class KenoBet {
    "nonce": number;
    "picks": number[];
    "draws": number[];
    "hits": number;
    "multiplier": number;

    /** Creates a new KenoBet instance. */
    constructor($$source: Partial<KenoBet> = {}) {
        if (!("nonce" in $$source)) {
            this["nonce"] = 0;
        }
        if (!("picks" in $$source)) {
            this["picks"] = [];
        }
        if (!("draws" in $$source)) {
            this["draws"] = [];
        }
        if (!("hits" in $$source)) {
            this["hits"] = 0;
        }
        if (!("multiplier" in $$source)) {
            this["multiplier"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KenoBet instance from a string or object.
     */
    static createFrom($$source: any = {}): KenoBet {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("picks" in $$parsedSource) {
            $$parsedSource["picks"] = $$createField1_0($$parsedSource["picks"]);
        }
        if ("draws" in $$parsedSource) {
            $$parsedSource["draws"] = $$createField2_0($$parsedSource["draws"]);
        }
        return new KenoBet($$parsedSource as Partial<KenoBet>);
    }
}

/**
 * RunsList represents paginated runs response
 */
export class RunsList {
    "runs": store$0.Run[];
    "totalCount": number;
    "page": number;
    "perPage": number;
    "totalPages": number;

    /** Creates a new RunsList instance. */
    constructor($$source: Partial<RunsList> = {}) {
        if (!("runs" in $$source)) {
            this["runs"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("perPage" in $$source)) {
            this["perPage"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunsList instance from a string or object.
     */
    static createFrom($$source: any = {}): RunsList {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runs" in $$parsedSource) {
            $$parsedSource["runs"] = $$createField0_0($$parsedSource["runs"]);
        }
        return new RunsList($$parsedSource as Partial<RunsList>);
    }
}

/**
 * RunsQuery represents query parameters for listing runs
 */
export class RunsQuery {
    "game"?: string;
    "page": number;
    "perPage": number;

    /** Creates a new RunsQuery instance. */
    constructor($$source: Partial<RunsQuery> = {}) {
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("perPage" in $$source)) {
            this["perPage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunsQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): RunsQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunsQuery($$parsedSource as Partial<RunsQuery>);
    }
}

export class ScanRequest {
    "Game": string;
    "Seeds": Seeds;

    /**
     * Accept both string and uint64
     */
    "NonceStart": any;

    /**
     * Accept both string and uint64
     */
    "NonceEnd": any;
    "Params": { [_ in string]?: any };

    /**
     * Accept both string and TargetOp
     */
    "TargetOp": any;

    /**
     * Accept both string and float64
     */
    "TargetVal": any;
    "Tolerance": number;
    "Limit": number;
    "TimeoutMs": number;

    /** Creates a new ScanRequest instance. */
    constructor($$source: Partial<ScanRequest> = {}) {
        if (!("Game" in $$source)) {
            this["Game"] = "";
        }
        if (!("Seeds" in $$source)) {
            this["Seeds"] = (new Seeds());
        }
        if (!("NonceStart" in $$source)) {
            this["NonceStart"] = null;
        }
        if (!("NonceEnd" in $$source)) {
            this["NonceEnd"] = null;
        }
        if (!("Params" in $$source)) {
            this["Params"] = {};
        }
        if (!("TargetOp" in $$source)) {
            this["TargetOp"] = null;
        }
        if (!("TargetVal" in $$source)) {
            this["TargetVal"] = null;
        }
        if (!("Tolerance" in $$source)) {
            this["Tolerance"] = 0;
        }
        if (!("Limit" in $$source)) {
            this["Limit"] = 0;
        }
        if (!("TimeoutMs" in $$source)) {
            this["TimeoutMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanRequest {
        const $$createField1_0 = $$createType4;
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Seeds" in $$parsedSource) {
            $$parsedSource["Seeds"] = $$createField1_0($$parsedSource["Seeds"]);
        }
        if ("Params" in $$parsedSource) {
            $$parsedSource["Params"] = $$createField4_0($$parsedSource["Params"]);
        }
        return new ScanRequest($$parsedSource as Partial<ScanRequest>);
    }
}

export class ScanResult {
    "RunID": string;
    "Hits": Hit[];
    "Summary": Summary;
    "EngineVersion": string;
    "Echo": ScanRequest;
    "TimedOut": boolean;
    "ServerSeedHash": string;

    /** Creates a new ScanResult instance. */
    constructor($$source: Partial<ScanResult> = {}) {
        if (!("RunID" in $$source)) {
            this["RunID"] = "";
        }
        if (!("Hits" in $$source)) {
            this["Hits"] = [];
        }
        if (!("Summary" in $$source)) {
            this["Summary"] = (new Summary());
        }
        if (!("EngineVersion" in $$source)) {
            this["EngineVersion"] = "";
        }
        if (!("Echo" in $$source)) {
            this["Echo"] = (new ScanRequest());
        }
        if (!("TimedOut" in $$source)) {
            this["TimedOut"] = false;
        }
        if (!("ServerSeedHash" in $$source)) {
            this["ServerSeedHash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanResult {
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType13;
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Hits" in $$parsedSource) {
            $$parsedSource["Hits"] = $$createField1_0($$parsedSource["Hits"]);
        }
        if ("Summary" in $$parsedSource) {
            $$parsedSource["Summary"] = $$createField2_0($$parsedSource["Summary"]);
        }
        if ("Echo" in $$parsedSource) {
            $$parsedSource["Echo"] = $$createField4_0($$parsedSource["Echo"]);
        }
        return new ScanResult($$parsedSource as Partial<ScanResult>);
    }
}

/**
 * ScriptSessionSummary is a lightweight session entry for listing.
 */
export class ScriptSessionSummary {
    "id": string;
    "game": string;
    "currency": string;
    "mode": string;
    "finalState": string;
    "totalBets": number;
    "totalProfit": number;
    "startBalance": number;
    "finalBalance"?: number | null;
    "createdAt": string;
    "endedAt"?: string | null;

    /** Creates a new ScriptSessionSummary instance. */
    constructor($$source: Partial<ScriptSessionSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("finalState" in $$source)) {
            this["finalState"] = "";
        }
        if (!("totalBets" in $$source)) {
            this["totalBets"] = 0;
        }
        if (!("totalProfit" in $$source)) {
            this["totalProfit"] = 0;
        }
        if (!("startBalance" in $$source)) {
            this["startBalance"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptSessionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptSessionSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptSessionSummary($$parsedSource as Partial<ScriptSessionSummary>);
    }
}

/**
 * ScriptSessionsPage is a paginated sessions response.
 */
export class ScriptSessionsPage {
    "sessions": ScriptSessionSummary[];
    "totalCount": number;

    /** Creates a new ScriptSessionsPage instance. */
    constructor($$source: Partial<ScriptSessionsPage> = {}) {
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptSessionsPage instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptSessionsPage {
        const $$createField0_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField0_0($$parsedSource["sessions"]);
        }
        return new ScriptSessionsPage($$parsedSource as Partial<ScriptSessionsPage>);
    }
}

/**
 * ScriptState is the frontend-facing snapshot of engine state.
 */
export class ScriptState {
    "state": string;
    "error"?: string;
    "mode": string;
    "sessionId"?: string;
    "bets": number;
    "wins": number;
    "losses": number;
    "profit": number;
    "balance": number;
    "wagered": number;
    "winStreak": number;
    "loseStreak": number;
    "currentGame": string;
    "betsPerSecond": number;
    "chart": scripting$0.ChartPoint[];

    /** Creates a new ScriptState instance. */
    constructor($$source: Partial<ScriptState> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("bets" in $$source)) {
            this["bets"] = 0;
        }
        if (!("wins" in $$source)) {
            this["wins"] = 0;
        }
        if (!("losses" in $$source)) {
            this["losses"] = 0;
        }
        if (!("profit" in $$source)) {
            this["profit"] = 0;
        }
        if (!("balance" in $$source)) {
            this["balance"] = 0;
        }
        if (!("wagered" in $$source)) {
            this["wagered"] = 0;
        }
        if (!("winStreak" in $$source)) {
            this["winStreak"] = 0;
        }
        if (!("loseStreak" in $$source)) {
            this["loseStreak"] = 0;
        }
        if (!("currentGame" in $$source)) {
            this["currentGame"] = "";
        }
        if (!("betsPerSecond" in $$source)) {
            this["betsPerSecond"] = 0;
        }
        if (!("chart" in $$source)) {
            this["chart"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptState instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptState {
        const $$createField14_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chart" in $$parsedSource) {
            $$parsedSource["chart"] = $$createField14_0($$parsedSource["chart"]);
        }
        return new ScriptState($$parsedSource as Partial<ScriptState>);
    }
}

export class SeedGroupSeeds {
    "server": string;
    "serverHash": string;
    "client": string;

    /** Creates a new SeedGroupSeeds instance. */
    constructor($$source: Partial<SeedGroupSeeds> = {}) {
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("serverHash" in $$source)) {
            this["serverHash"] = "";
        }
        if (!("client" in $$source)) {
            this["client"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SeedGroupSeeds instance from a string or object.
     */
    static createFrom($$source: any = {}): SeedGroupSeeds {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SeedGroupSeeds($$parsedSource as Partial<SeedGroupSeeds>);
    }
}

export class SeedRunGroup {
    "seeds": SeedGroupSeeds;
    "runs": store$0.Run[];

    /** Creates a new SeedRunGroup instance. */
    constructor($$source: Partial<SeedRunGroup> = {}) {
        if (!("seeds" in $$source)) {
            this["seeds"] = (new SeedGroupSeeds());
        }
        if (!("runs" in $$source)) {
            this["runs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SeedRunGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): SeedRunGroup {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("seeds" in $$parsedSource) {
            $$parsedSource["seeds"] = $$createField0_0($$parsedSource["seeds"]);
        }
        if ("runs" in $$parsedSource) {
            $$parsedSource["runs"] = $$createField1_0($$parsedSource["runs"]);
        }
        return new SeedRunGroup($$parsedSource as Partial<SeedRunGroup>);
    }
}

export class Seeds {
    "Server": string;
    "Client": string;

    /** Creates a new Seeds instance. */
    constructor($$source: Partial<Seeds> = {}) {
        if (!("Server" in $$source)) {
            this["Server"] = "";
        }
        if (!("Client" in $$source)) {
            this["Client"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Seeds instance from a string or object.
     */
    static createFrom($$source: any = {}): Seeds {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Seeds($$parsedSource as Partial<Seeds>);
    }
}

export class Summary {
    "Count": number;
    "Min": number;
    "Max": number;
    "Sum": number;
    "TotalEvaluated": number;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }
        if (!("Min" in $$source)) {
            this["Min"] = 0;
        }
        if (!("Max" in $$source)) {
            this["Max"] = 0;
        }
        if (!("Sum" in $$source)) {
            this["Sum"] = 0;
        }
        if (!("TotalEvaluated" in $$source)) {
            this["TotalEvaluated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = KenoBet.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = store$0.HitWithDelta.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Seeds.createFrom;
const $$createType5 = B2BSequence.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = store$0.Run.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = Hit.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = Summary.createFrom;
const $$createType14 = ScanRequest.createFrom;
const $$createType15 = ScriptSessionSummary.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = scripting$0.ChartPoint.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = SeedGroupSeeds.createFrom;
