// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScriptModule is the Wails-bound struct for scripting engine management.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scripting$0 from "../internal/scripting/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scriptstore$0 from "../internal/scriptstore/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteScriptSession removes a session and all associated data.
 */
export function DeleteScriptSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(452655314, id);
}

/**
 * GetScriptLog returns the script log buffer.
 */
export function GetScriptLog(): $CancellablePromise<scripting$0.LogEntry[]> {
    return $Call.ByID(1219514917).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetScriptSession returns the full details of a session by ID.
 */
export function GetScriptSession(id: string): $CancellablePromise<scriptstore$0.ScriptSession | null> {
    return $Call.ByID(1229502875, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetScriptSessionBets returns paginated bets for a session.
 */
export function GetScriptSessionBets(id: string, page: number, perPage: number): $CancellablePromise<scriptstore$0.ScriptBetsPage | null> {
    return $Call.ByID(4272327387, id, page, perPage).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetScriptState returns the current scripting engine state.
 */
export function GetScriptState(): $CancellablePromise<$models.ScriptState> {
    return $Call.ByID(2140085210).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * InitStore initializes the script session store at the given path.
 * Should be called during application startup.
 */
export function InitStore(dbPath: string): $CancellablePromise<void> {
    return $Call.ByID(134064029, dbPath);
}

/**
 * ListScriptSessions returns paginated script sessions.
 */
export function ListScriptSessions(limit: number, offset: number): $CancellablePromise<$models.ScriptSessionsPage> {
    return $Call.ByID(3436436008, limit, offset).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * StartScript starts the scripting engine with the given script.
 * mode: "simulated" (default) or "live" (uses real Stake API).
 */
export function StartScript(script: string, game: string, currency: string, startBalance: number, mode: string): $CancellablePromise<void> {
    return $Call.ByID(1794405877, script, game, currency, startBalance, mode);
}

/**
 * StartScriptWithSafety starts a script with explicit backend-enforced limits.
 */
export function StartScriptWithSafety(script: string, game: string, currency: string, startBalance: number, mode: string, safety: scripting$0.SafetyLimits): $CancellablePromise<void> {
    return $Call.ByID(4053723219, script, game, currency, startBalance, mode, safety);
}

/**
 * Startup is called by Wails on application startup.
 */
export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(634781579);
}

/**
 * StopScript stops the currently running script.
 */
export function StopScript(): $CancellablePromise<void> {
    return $Call.ByID(2018195853);
}

// Private type creation functions
const $$createType0 = scripting$0.LogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = scriptstore$0.ScriptSession.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = scriptstore$0.ScriptBetsPage.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.ScriptState.createFrom;
const $$createType7 = $models.ScriptSessionsPage.createFrom;
