// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stake} from '../models';
import {stakeauth} from '../models';
import {context} from '../models';

export function ActiveAccountID():Promise<string>;

export function ActiveConnectionState():Promise<string>;

export function Client():Promise<stake.Client>;

export function Connect(arg1:string):Promise<void>;

export function ConnectionCheck(arg1:string):Promise<stakeauth.ConnectionCheckResult>;

export function DeleteAccount(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetActiveStatus():Promise<stakeauth.ActiveStatus>;

export function GetSecretsMasked(arg1:string):Promise<stakeauth.SecretsMasked>;

export function IsConnected():Promise<boolean>;

export function ListAccounts():Promise<Array<stakeauth.Account>>;

export function MarkSessionFailure(arg1:stake.ErrorKind,arg2:string):Promise<void>;

export function OpenCasinoInBrowser(arg1:string):Promise<void>;

export function RepairSession(arg1:string):Promise<void>;

export function SaveAccount(arg1:stakeauth.Account):Promise<stakeauth.Account>;

export function SetSecrets(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
