// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveConnectionState() {
  return window['go']['bindings']['AuthModule']['ActiveConnectionState']();
}

export function Client() {
  return window['go']['bindings']['AuthModule']['Client']();
}

export function Connect(arg1) {
  return window['go']['bindings']['AuthModule']['Connect'](arg1);
}

export function ConnectionCheck(arg1) {
  return window['go']['bindings']['AuthModule']['ConnectionCheck'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['bindings']['AuthModule']['DeleteAccount'](arg1);
}

export function Disconnect() {
  return window['go']['bindings']['AuthModule']['Disconnect']();
}

export function GetActiveStatus() {
  return window['go']['bindings']['AuthModule']['GetActiveStatus']();
}

export function GetSecretsMasked(arg1) {
  return window['go']['bindings']['AuthModule']['GetSecretsMasked'](arg1);
}

export function IsConnected() {
  return window['go']['bindings']['AuthModule']['IsConnected']();
}

export function ListAccounts() {
  return window['go']['bindings']['AuthModule']['ListAccounts']();
}

export function OpenCasinoInBrowser(arg1) {
  return window['go']['bindings']['AuthModule']['OpenCasinoInBrowser'](arg1);
}

export function RepairSession(arg1) {
  return window['go']['bindings']['AuthModule']['RepairSession'](arg1);
}

export function SaveAccount(arg1) {
  return window['go']['bindings']['AuthModule']['SaveAccount'](arg1);
}

export function SetSecrets(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['AuthModule']['SetSecrets'](arg1, arg2, arg3, arg4);
}

export function Shutdown() {
  return window['go']['bindings']['AuthModule']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['bindings']['AuthModule']['Startup'](arg1);
}
