// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scripting} from '../models';
import {scriptstore} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function DeleteScriptSession(arg1:string):Promise<void>;

export function GetScriptLog():Promise<Array<scripting.LogEntry>>;

export function GetScriptSession(arg1:string):Promise<scriptstore.ScriptSession>;

export function GetScriptSessionBets(arg1:string,arg2:number,arg3:number):Promise<scriptstore.ScriptBetsPage>;

export function GetScriptState():Promise<bindings.ScriptState>;

export function InitStore(arg1:string):Promise<void>;

export function ListScriptSessions(arg1:number,arg2:number):Promise<bindings.ScriptSessionsPage>;

export function StartScript(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<void>;

export function StartScriptWithOptions(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:bindings.LiveScriptOptions):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopScript():Promise<void>;
