// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteScriptSession(arg1) {
  return window['go']['bindings']['ScriptModule']['DeleteScriptSession'](arg1);
}

export function GetScriptLog() {
  return window['go']['bindings']['ScriptModule']['GetScriptLog']();
}

export function GetScriptSession(arg1) {
  return window['go']['bindings']['ScriptModule']['GetScriptSession'](arg1);
}

export function GetScriptSessionBets(arg1, arg2, arg3) {
  return window['go']['bindings']['ScriptModule']['GetScriptSessionBets'](arg1, arg2, arg3);
}

export function GetScriptState() {
  return window['go']['bindings']['ScriptModule']['GetScriptState']();
}

export function InitStore(arg1) {
  return window['go']['bindings']['ScriptModule']['InitStore'](arg1);
}

export function ListScriptSessions(arg1, arg2) {
  return window['go']['bindings']['ScriptModule']['ListScriptSessions'](arg1, arg2);
}

export function StartScript(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bindings']['ScriptModule']['StartScript'](arg1, arg2, arg3, arg4, arg5);
}

export function StartScriptWithOptions(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['bindings']['ScriptModule']['StartScriptWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Startup(arg1) {
  return window['go']['bindings']['ScriptModule']['Startup'](arg1);
}

export function StopScript() {
  return window['go']['bindings']['ScriptModule']['StopScript']();
}
