// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../../../google/uuid/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class LiveBet {
    "id": number;
    "stream_id": uuid$0.UUID;
    "antebot_bet_id": string;
    "received_at": time$0.Time;
    "date_time": time$0.Time;
    "nonce": number;
    "amount": number;
    "payout": number;
    "difficulty": string;
    "round_target": number;
    "round_result": number;

    /** Creates a new LiveBet instance. */
    constructor($$source: Partial<LiveBet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("stream_id" in $$source)) {
            this["stream_id"] = "";
        }
        if (!("antebot_bet_id" in $$source)) {
            this["antebot_bet_id"] = "";
        }
        if (!("received_at" in $$source)) {
            this["received_at"] = null;
        }
        if (!("date_time" in $$source)) {
            this["date_time"] = null;
        }
        if (!("nonce" in $$source)) {
            this["nonce"] = 0;
        }
        if (!("amount" in $$source)) {
            this["amount"] = 0;
        }
        if (!("payout" in $$source)) {
            this["payout"] = 0;
        }
        if (!("difficulty" in $$source)) {
            this["difficulty"] = "";
        }
        if (!("round_target" in $$source)) {
            this["round_target"] = 0;
        }
        if (!("round_result" in $$source)) {
            this["round_result"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveBet instance from a string or object.
     */
    static createFrom($$source: any = {}): LiveBet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveBet($$parsedSource as Partial<LiveBet>);
    }
}

/**
 * LiveRound represents a single round observation from heartbeat data.
 */
export class LiveRound {
    "id": number;
    "stream_id": uuid$0.UUID;
    "nonce": number;
    "round_result": number;
    "received_at": time$0.Time;

    /** Creates a new LiveRound instance. */
    constructor($$source: Partial<LiveRound> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("stream_id" in $$source)) {
            this["stream_id"] = "";
        }
        if (!("nonce" in $$source)) {
            this["nonce"] = 0;
        }
        if (!("round_result" in $$source)) {
            this["round_result"] = 0;
        }
        if (!("received_at" in $$source)) {
            this["received_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveRound instance from a string or object.
     */
    static createFrom($$source: any = {}): LiveRound {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveRound($$parsedSource as Partial<LiveRound>);
    }
}

export class LiveStream {
    "id": uuid$0.UUID;
    "server_seed_hashed": string;
    "client_seed": string;
    "created_at": time$0.Time;
    "last_seen_at": time$0.Time;
    "notes": string;
    "total_bets": number;
    "highest_result": number;
    "last_observed_nonce": number;
    "last_observed_at": time$0.Time;

    /** Creates a new LiveStream instance. */
    constructor($$source: Partial<LiveStream> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("server_seed_hashed" in $$source)) {
            this["server_seed_hashed"] = "";
        }
        if (!("client_seed" in $$source)) {
            this["client_seed"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("last_seen_at" in $$source)) {
            this["last_seen_at"] = null;
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("total_bets" in $$source)) {
            this["total_bets"] = 0;
        }
        if (!("highest_result" in $$source)) {
            this["highest_result"] = 0;
        }
        if (!("last_observed_nonce" in $$source)) {
            this["last_observed_nonce"] = 0;
        }
        if (!("last_observed_at" in $$source)) {
            this["last_observed_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveStream instance from a string or object.
     */
    static createFrom($$source: any = {}): LiveStream {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveStream($$parsedSource as Partial<LiveStream>);
    }
}
