// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ScriptBet represents a single bet within a session.
 */
export class ScriptBet {
    "id": number;
    "sessionId": string;
    "nonce": number;
    "amount": number;
    "payout": number;
    "payoutMulti": number;
    "win": boolean;
    "roll"?: number | null;
    "createdAt": time$0.Time;

    /** Creates a new ScriptBet instance. */
    constructor($$source: Partial<ScriptBet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("nonce" in $$source)) {
            this["nonce"] = 0;
        }
        if (!("amount" in $$source)) {
            this["amount"] = 0;
        }
        if (!("payout" in $$source)) {
            this["payout"] = 0;
        }
        if (!("payoutMulti" in $$source)) {
            this["payoutMulti"] = 0;
        }
        if (!("win" in $$source)) {
            this["win"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptBet instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptBet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptBet($$parsedSource as Partial<ScriptBet>);
    }
}

/**
 * ScriptBetsPage is a paginated bets response.
 */
export class ScriptBetsPage {
    "bets": ScriptBet[];
    "totalCount": number;
    "page": number;
    "perPage": number;
    "totalPages": number;

    /** Creates a new ScriptBetsPage instance. */
    constructor($$source: Partial<ScriptBetsPage> = {}) {
        if (!("bets" in $$source)) {
            this["bets"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("perPage" in $$source)) {
            this["perPage"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptBetsPage instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptBetsPage {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bets" in $$parsedSource) {
            $$parsedSource["bets"] = $$createField0_0($$parsedSource["bets"]);
        }
        return new ScriptBetsPage($$parsedSource as Partial<ScriptBetsPage>);
    }
}

/**
 * ScriptSession represents a scripting engine session.
 */
export class ScriptSession {
    "id": string;
    "name": string;
    "game": string;
    "currency": string;
    "mode": string;
    "scriptSource": string;
    "startBalance": number;
    "finalBalance"?: number | null;
    "createdAt": time$0.Time;
    "endedAt"?: time$0.Time | null;
    "finalState": string;
    "totalBets": number;
    "totalWins": number;
    "totalLosses": number;
    "totalProfit": number;
    "totalWagered": number;
    "highestStreak": number;
    "lowestStreak": number;

    /** Creates a new ScriptSession instance. */
    constructor($$source: Partial<ScriptSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("scriptSource" in $$source)) {
            this["scriptSource"] = "";
        }
        if (!("startBalance" in $$source)) {
            this["startBalance"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("finalState" in $$source)) {
            this["finalState"] = "";
        }
        if (!("totalBets" in $$source)) {
            this["totalBets"] = 0;
        }
        if (!("totalWins" in $$source)) {
            this["totalWins"] = 0;
        }
        if (!("totalLosses" in $$source)) {
            this["totalLosses"] = 0;
        }
        if (!("totalProfit" in $$source)) {
            this["totalProfit"] = 0;
        }
        if (!("totalWagered" in $$source)) {
            this["totalWagered"] = 0;
        }
        if (!("highestStreak" in $$source)) {
            this["highestStreak"] = 0;
        }
        if (!("lowestStreak" in $$source)) {
            this["lowestStreak"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptSession instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptSession($$parsedSource as Partial<ScriptSession>);
    }
}

// Private type creation functions
const $$createType0 = ScriptBet.createFrom;
const $$createType1 = $Create.Array($$createType0);
