// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * HitWithDelta represents a hit with calculated delta nonce
 */
export class HitWithDelta {
    "id": number;
    "run_id": string;
    "nonce": number;
    "metric": number;

    /**
     * JSON string
     */
    "details": string;
    "delta_nonce"?: number | null;

    /** Creates a new HitWithDelta instance. */
    constructor($$source: Partial<HitWithDelta> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("run_id" in $$source)) {
            this["run_id"] = "";
        }
        if (!("nonce" in $$source)) {
            this["nonce"] = 0;
        }
        if (!("metric" in $$source)) {
            this["metric"] = 0;
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HitWithDelta instance from a string or object.
     */
    static createFrom($$source: any = {}): HitWithDelta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HitWithDelta($$parsedSource as Partial<HitWithDelta>);
    }
}

/**
 * Run represents a scan run
 */
export class Run {
    "id": string;
    "game": string;

    /**
     * Deprecated: for backward compatibility
     */
    "server_seed": string;

    /**
     * SHA256 hash only
     */
    "server_seed_hash": string;
    "client_seed": string;
    "nonce_start": number;
    "nonce_end": number;
    "params_json": string;
    "target_op": string;
    "target_val": number;
    "tolerance": number;
    "hit_limit": number;
    "timed_out": boolean;
    "hit_count": number;
    "total_evaluated": number;
    "summary_min": number | null;
    "summary_max": number | null;
    "summary_sum": number | null;
    "summary_count": number;
    "engine_version": string;
    "created_at": time$0.Time;

    /** Creates a new Run instance. */
    constructor($$source: Partial<Run> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }
        if (!("server_seed" in $$source)) {
            this["server_seed"] = "";
        }
        if (!("server_seed_hash" in $$source)) {
            this["server_seed_hash"] = "";
        }
        if (!("client_seed" in $$source)) {
            this["client_seed"] = "";
        }
        if (!("nonce_start" in $$source)) {
            this["nonce_start"] = 0;
        }
        if (!("nonce_end" in $$source)) {
            this["nonce_end"] = 0;
        }
        if (!("params_json" in $$source)) {
            this["params_json"] = "";
        }
        if (!("target_op" in $$source)) {
            this["target_op"] = "";
        }
        if (!("target_val" in $$source)) {
            this["target_val"] = 0;
        }
        if (!("tolerance" in $$source)) {
            this["tolerance"] = 0;
        }
        if (!("hit_limit" in $$source)) {
            this["hit_limit"] = 0;
        }
        if (!("timed_out" in $$source)) {
            this["timed_out"] = false;
        }
        if (!("hit_count" in $$source)) {
            this["hit_count"] = 0;
        }
        if (!("total_evaluated" in $$source)) {
            this["total_evaluated"] = 0;
        }
        if (!("summary_min" in $$source)) {
            this["summary_min"] = null;
        }
        if (!("summary_max" in $$source)) {
            this["summary_max"] = null;
        }
        if (!("summary_sum" in $$source)) {
            this["summary_sum"] = null;
        }
        if (!("summary_count" in $$source)) {
            this["summary_count"] = 0;
        }
        if (!("engine_version" in $$source)) {
            this["engine_version"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Run instance from a string or object.
     */
    static createFrom($$source: any = {}): Run {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Run($$parsedSource as Partial<Run>);
    }
}
