// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteStream(arg1) {
  return window['go']['livehttp']['LiveModule']['DeleteStream'](arg1);
}

export function EmitManualTick(arg1) {
  return window['go']['livehttp']['LiveModule']['EmitManualTick'](arg1);
}

export function ExportCSV(arg1) {
  return window['go']['livehttp']['LiveModule']['ExportCSV'](arg1);
}

export function GetBets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['livehttp']['LiveModule']['GetBets'](arg1, arg2, arg3, arg4, arg5);
}

export function GetBetsPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['livehttp']['LiveModule']['GetBetsPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetRecentRounds(arg1, arg2) {
  return window['go']['livehttp']['LiveModule']['GetRecentRounds'](arg1, arg2);
}

export function GetRoundsPage(arg1, arg2, arg3, arg4) {
  return window['go']['livehttp']['LiveModule']['GetRoundsPage'](arg1, arg2, arg3, arg4);
}

export function GetStream(arg1) {
  return window['go']['livehttp']['LiveModule']['GetStream'](arg1);
}

export function GetStreamWithRounds(arg1, arg2) {
  return window['go']['livehttp']['LiveModule']['GetStreamWithRounds'](arg1, arg2);
}

export function IngestInfo() {
  return window['go']['livehttp']['LiveModule']['IngestInfo']();
}

export function ListAppBets(arg1, arg2, arg3, arg4) {
  return window['go']['livehttp']['LiveModule']['ListAppBets'](arg1, arg2, arg3, arg4);
}

export function ListStreams(arg1, arg2) {
  return window['go']['livehttp']['LiveModule']['ListStreams'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['livehttp']['LiveModule']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['livehttp']['LiveModule']['Startup'](arg1);
}

export function Tail(arg1, arg2, arg3) {
  return window['go']['livehttp']['LiveModule']['Tail'](arg1, arg2, arg3);
}

export function TailRounds(arg1, arg2, arg3) {
  return window['go']['livehttp']['LiveModule']['TailRounds'](arg1, arg2, arg3);
}

export function UpdateNotes(arg1, arg2) {
  return window['go']['livehttp']['LiveModule']['UpdateNotes'](arg1, arg2);
}
