// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LiveModule is a Wails-bound service that owns the DB and the local HTTP ingest server.
 * UI calls its methods directly (bindings). Antebot posts to the local HTTP server.
 * The module emits UI events on new rows via the ingest handler.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as livestore$0 from "../livestore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteStream removes a stream and all its bets.
 */
export function DeleteStream(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(96583583, streamID);
}

/**
 * EmitManualTick lets the UI force a "newrows" event (useful for testing the wiring).
 */
export function EmitManualTick(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(2621318640, streamID);
}

/**
 * ExportCSV writes all bets for a stream to a temp CSV and returns the path.
 * The file contains header: id,nonce,date_time,amount,payout,difficulty,round_target,round_result
 */
export function ExportCSV(streamID: string): $CancellablePromise<string> {
    return $Call.ByID(3126652834, streamID);
}

/**
 * GetBets returns a page of bets for a stream.
 * order: "asc" (by nonce asc) or "desc" (by nonce desc). Any other value defaults to "asc".
 */
export function GetBets(streamID: string, minMultiplier: number, order: string, limit: number, offset: number): $CancellablePromise<[livestore$0.LiveBet[], number]> {
    return $Call.ByID(119239740, streamID, minMultiplier, order, limit, offset).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    });
}

/**
 * GetBetsPage returns the bets page along with the total row count.
 */
export function GetBetsPage(streamID: string, minMultiplier: number, order: string, limit: number, offset: number): $CancellablePromise<$models.BetsPage> {
    return $Call.ByID(1819530199, streamID, minMultiplier, order, limit, offset).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRecentRounds returns the most recent N rounds for a stream (for pattern visualization).
 */
export function GetRecentRounds(streamID: string, limit: number): $CancellablePromise<livestore$0.LiveRound[]> {
    return $Call.ByID(3095428294, streamID, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetRoundsPage returns paginated rounds with optional min_result filter.
 */
export function GetRoundsPage(streamID: string, minResult: number, limit: number, offset: number): $CancellablePromise<$models.RoundsPage> {
    return $Call.ByID(1832703970, streamID, minResult, limit, offset).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetStream returns metadata and aggregates for a stream.
 */
export function GetStream(streamID: string): $CancellablePromise<livestore$0.LiveStream> {
    return $Call.ByID(2795336976, streamID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetStreamWithRounds returns stream details plus recent rounds for initial dashboard load.
 */
export function GetStreamWithRounds(streamID: string, roundsLimit: number): $CancellablePromise<$models.StreamWithRounds> {
    return $Call.ByID(1936288281, streamID, roundsLimit).then(($result: any) => {
        return $$createType7($result);
    });
}

export function IngestInfo(): $CancellablePromise<$models.IngestInfo> {
    return $Call.ByID(2435386624).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListStreams returns recent streams with aggregates, ordered by last_seen_at desc.
 */
export function ListStreams(limit: number, offset: number): $CancellablePromise<livestore$0.LiveStream[]> {
    return $Call.ByID(1795990421, limit, offset).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3790929378, app);
}

/**
 * Shutdown stops the HTTP server and closes the DB.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(2427432510);
}

/**
 * Startup stores the Wails context and starts the local HTTP server.
 */
export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(2818583397);
}

export function Tail(streamID: string, sinceID: number, limit: number): $CancellablePromise<$models.TailResponse> {
    return $Call.ByID(1668402662, streamID, sinceID, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * TailRounds returns rounds with nonce > sinceNonce for live updates.
 */
export function TailRounds(streamID: string, sinceNonce: number, limit: number): $CancellablePromise<$models.TailRoundsResponse> {
    return $Call.ByID(3117501495, streamID, sinceNonce, limit).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * UpdateNotes sets the notes field on a stream.
 */
export function UpdateNotes(streamID: string, notes: string): $CancellablePromise<void> {
    return $Call.ByID(921956890, streamID, notes);
}

// Private type creation functions
const $$createType0 = livestore$0.LiveBet.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.BetsPage.createFrom;
const $$createType3 = livestore$0.LiveRound.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.RoundsPage.createFrom;
const $$createType6 = livestore$0.LiveStream.createFrom;
const $$createType7 = $models.StreamWithRounds.createFrom;
const $$createType8 = $models.IngestInfo.createFrom;
const $$createType9 = $Create.Array($$createType6);
const $$createType10 = $models.TailResponse.createFrom;
const $$createType11 = $models.TailRoundsResponse.createFrom;
