// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as livestore$0 from "../livestore/models.js";

/**
 * BetsPage is a convenience wrapper exposing both rows and total for frontend consumption.
 */
export class BetsPage {
    "rows": livestore$0.LiveBet[];
    "total": number;

    /** Creates a new BetsPage instance. */
    constructor($$source: Partial<BetsPage> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BetsPage instance from a string or object.
     */
    static createFrom($$source: any = {}): BetsPage {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new BetsPage($$parsedSource as Partial<BetsPage>);
    }
}

/**
 * IngestInfo returns the loopback URL Antebot should post to and whether a token is required.
 * Useful to render in a Settings/About UI.
 */
export class IngestInfo {
    "url": string;
    "tokenEnabled": boolean;

    /** Creates a new IngestInfo instance. */
    constructor($$source: Partial<IngestInfo> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("tokenEnabled" in $$source)) {
            this["tokenEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IngestInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IngestInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IngestInfo($$parsedSource as Partial<IngestInfo>);
    }
}

/**
 * RoundsPage is a convenience wrapper for paginated rounds.
 */
export class RoundsPage {
    "rows": livestore$0.LiveRound[];
    "total": number;

    /** Creates a new RoundsPage instance. */
    constructor($$source: Partial<RoundsPage> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoundsPage instance from a string or object.
     */
    static createFrom($$source: any = {}): RoundsPage {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new RoundsPage($$parsedSource as Partial<RoundsPage>);
    }
}

/**
 * StreamWithRounds combines stream metadata with recent rounds in one call.
 */
export class StreamWithRounds {
    "stream": livestore$0.LiveStream;
    "rounds": livestore$0.LiveRound[];

    /** Creates a new StreamWithRounds instance. */
    constructor($$source: Partial<StreamWithRounds> = {}) {
        if (!("stream" in $$source)) {
            this["stream"] = (new livestore$0.LiveStream());
        }
        if (!("rounds" in $$source)) {
            this["rounds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamWithRounds instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamWithRounds {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stream" in $$parsedSource) {
            $$parsedSource["stream"] = $$createField0_0($$parsedSource["stream"]);
        }
        if ("rounds" in $$parsedSource) {
            $$parsedSource["rounds"] = $$createField1_0($$parsedSource["rounds"]);
        }
        return new StreamWithRounds($$parsedSource as Partial<StreamWithRounds>);
    }
}

/**
 * Tail returns bets with id > sinceID ordered by id ASC and the new lastID.
 */
export class TailResponse {
    "rows": livestore$0.LiveBet[];
    "lastID": number;

    /** Creates a new TailResponse instance. */
    constructor($$source: Partial<TailResponse> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("lastID" in $$source)) {
            this["lastID"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TailResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TailResponse {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new TailResponse($$parsedSource as Partial<TailResponse>);
    }
}

/**
 * TailRoundsResponse contains rounds since a given nonce.
 */
export class TailRoundsResponse {
    "rows": livestore$0.LiveRound[];
    "lastNonce": number;

    /** Creates a new TailRoundsResponse instance. */
    constructor($$source: Partial<TailRoundsResponse> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("lastNonce" in $$source)) {
            this["lastNonce"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TailRoundsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TailRoundsResponse {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new TailRoundsResponse($$parsedSource as Partial<TailRoundsResponse>);
    }
}

// Private type creation functions
const $$createType0 = livestore$0.LiveBet.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = livestore$0.LiveRound.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = livestore$0.LiveStream.createFrom;
